### ISSUE TITLE
NRE 

### ISSUE THREAD

**Issue by jazzdelightsme** [jazzdelightsme/OneNotePowerShellProvider#1]
# Repro steps:
```powershell
cd onenote:\
new-item testNotebook -Type
```
then hit <kbd>tab</kbd> to attempt tab completion

# Expected result:
it all works

# Actual result:

```none
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Office.OneNote.PowerShell
  StackTrace:
   at Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.PathIsDrive(String path) in \OneNotePowerShellProvider\Provider\OneNoteProvider.cs:line 779
```
(`this.PSDriveInfo` is null; we tried to access `this.PSDriveInfo.Root`)

Stack:
```
>	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.PathIsDrive(string path) Line 779	C#
 	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.getOneNoteNode(string path) Line 510	C#
 	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.ItemExists(string path) Line 123	C#
```

**Comment by jazzdelightsme** [comment]
Oh, and if you attempt to continue execution, there are plenty more NREs after that, like:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.MshCommandRuntime.ThrowIfWriteNotPermitted(Boolean needsToWriteToPipeline)
   at System.Management.Automation.MshCommandRuntime.WriteHelper_ShouldWrite(ActionPreference preference, ContinueStatus lastContinueStatus)
   at System.Management.Automation.MshCommandRuntime.WriteDebug(DebugRecord record, Boolean overrideInquire)
   at System.Management.Automation.Cmdlet.WriteDebug(String text)
   at System.Management.Automation.Provider.CmdletProvider.WriteDebug(String text)
   at Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.getChildNodeByName(XmlNode parentElement, String component) in \OneNotePowerShellProvider\Provider\OneNoteProvider.cs:line 635
```

Stack:
```
 	System.Management.Automation.dll!System.Management.Automation.MshCommandRuntime.ThrowIfWriteNotPermitted(bool needsToWriteToPipeline)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.MshCommandRuntime.WriteHelper_ShouldWrite(System.Management.Automation.ActionPreference preference, System.Management.Automation.MshCommandRuntime.ContinueStatus lastContinueStatus)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.MshCommandRuntime.WriteDebug(System.Management.Automation.DebugRecord record, bool overrideInquire)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Cmdlet.WriteDebug(string text)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Provider.CmdletProvider.WriteDebug(string text)	Unknown
 	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.getChildNodeByName(System.Xml.XmlNode parentElement, string component) Line 635	C#
 	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.getOneNoteNode(string path) Line 528	C#
 	Microsoft.Office.OneNote.PowerShell.dll!Microsoft.Office.OneNote.PowerShell.Provider.OneNoteProvider.ItemExists(string path) Line 123	C#
 	System.Management.Automation.dll!System.Management.Automation.Provider.ItemCmdletProvider.ItemExists(string path, System.Management.Automation.CmdletProviderContext context)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Provider.NavigationCmdletProvider.GetChildName(string path)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Provider.NavigationCmdletProvider.TokenizePathToStack(string path, string basePath)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Provider.NavigationCmdletProvider.ContractRelativePath(string path, string basePath, bool allowNonExistingPaths, System.Management.Automation.CmdletProviderContext context)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.LocationGlobber.GenerateRelativePath(System.Management.Automation.PSDriveInfo drive, string path, bool escapeCurrentLocation, System.Management.Automation.Provider.CmdletProvider providerInstance, System.Management.Automation.CmdletProviderContext context)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.LocationGlobber.GetDriveRootRelativePathFromPSPath(string path, System.Management.Automation.CmdletProviderContext context, bool escapeCurrentLocation, out System.Management.Automation.PSDriveInfo workingDriveForPath, out System.Management.Automation.Provider.CmdletProvider providerInstance)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.LocationGlobber.GetProviderPath(string path, System.Management.Automation.CmdletProviderContext context, bool isTrusted, out System.Management.Automation.ProviderInfo provider, out System.Management.Automation.PSDriveInfo drive)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(string path, bool allowNonexistingPaths, System.Management.Automation.CmdletProviderContext context, out System.Management.Automation.ProviderInfo provider, out System.Management.Automation.Provider.CmdletProvider providerInstance)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.SessionStateInternal.NewItemDynamicParameters(string path, string type, object newItemValue, System.Management.Automation.CmdletProviderContext context)	Unknown
 	Microsoft.PowerShell.Commands.Management.dll!Microsoft.PowerShell.Commands.NewItemCommand.GetDynamicParameters(System.Management.Automation.CmdletProviderContext context)	Unknown
 	Microsoft.PowerShell.Commands.Management.dll!Microsoft.PowerShell.Commands.CoreCommandBase.GetDynamicParameters()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(out System.Management.Automation.ParameterBindingException outgoingBindingException)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(System.Collections.ObjectModel.Collection<System.Management.Automation.CommandParameterInternal> arguments)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Language.PseudoParameterBinder.PrepareCommandElements(System.Management.Automation.ExecutionContext context)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Language.PseudoParameterBinder.DoPseudoParameterBinding(System.Management.Automation.Language.CommandAst command, System.Type pipeArgumentType, System.Management.Automation.Language.CommandParameterAst paramAstAtCursor, System.Management.Automation.Language.PseudoParameterBinder.BindingType bindingType)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CompletionCompleters.CompleteCommandArgument(System.Management.Automation.CompletionContext context)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CompletionAnalysis.GetResultForIdentifier(System.Management.Automation.CompletionContext completionContext, ref int replacementIndex, ref int replacementLength, bool isQuotedString)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CompletionAnalysis.GetResultHelper(System.Management.Automation.CompletionContext completionContext, out int replacementIndex, out int replacementLength, bool isQuotedString)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CompletionAnalysis.GetResults(System.Management.Automation.PowerShell powerShell, out int replacementIndex, out int replacementLength)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CommandCompletion.CompleteInputImpl(System.Management.Automation.Language.Ast ast, System.Management.Automation.Language.Token[] tokens, System.Management.Automation.Language.IScriptPosition positionOfCursor, System.Collections.Hashtable options)	Unknown
 	[Lightweight Function]	
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.DynamicInstruction<System.Type, string, int, System.Collections.Hashtable, object>.Run(System.Management.Automation.Interpreter.InterpretedFrame frame)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame frame)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame frame)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame frame)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame frame)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Interpreter.LightLambda.RunVoid1<System.Management.Automation.Language.FunctionContext>(System.Management.Automation.Language.FunctionContext arg0)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PSScriptCmdlet.RunClause(System.Action<System.Management.Automation.Language.FunctionContext> clause, object dollarUnderbar, object inputToProcess)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PSScriptCmdlet.DoEndProcessing()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CommandProcessorBase.Complete()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CommandProcessorBase.DoComplete()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase commandRequestingUpstreamCommandsToStop)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(object input)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(System.Collections.IEnumerable input, bool syncCall)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.Runspaces.PipelineBase.Invoke(System.Collections.IEnumerable input)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(System.Management.Automation.Runspaces.Runspace rs, bool performSyncInvoke)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PowerShell.CoreInvokeHelper<object, System.Management.Automation.PSObject>(System.Management.Automation.PSDataCollection<object> input, System.Management.Automation.PSDataCollection<System.Management.Automation.PSObject> output, System.Management.Automation.PSInvocationSettings settings)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PowerShell.CoreInvoke<object, System.Management.Automation.PSObject>(System.Management.Automation.PSDataCollection<object> input, System.Management.Automation.PSDataCollection<System.Management.Automation.PSObject> output, System.Management.Automation.PSInvocationSettings settings)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.PowerShell.Invoke(System.Collections.IEnumerable input, System.Management.Automation.PSInvocationSettings settings)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CommandCompletion.CallScriptWithStringParameterSet(string input, int cursorIndex, System.Collections.Hashtable options, System.Management.Automation.PowerShell powershell)	Unknown
 	System.Management.Automation.dll!System.Management.Automation.CommandCompletion.CompleteInput(string input, int cursorIndex, System.Collections.Hashtable options, System.Management.Automation.PowerShell powershell)	Unknown
 	Microsoft.PowerShell.PSReadLine2.dll!PlatformWindows.CallPossibleExternalApplication<System.__Canon>(System.Func<System.__Canon> func)	Unknown
 	Microsoft.PowerShell.PSReadLine2.dll!Microsoft.PowerShell.PSConsoleReadLine.CallPossibleExternalApplication<System.Management.Automation.CommandCompletion>(System.Func<System.Management.Automation.CommandCompletion> func)	Unknown
 	Microsoft.PowerShell.PSReadLine2.dll!Microsoft.PowerShell.PSConsoleReadLine.GetCompletions()	Unknown
 	Microsoft.PowerShell.PSReadLine2.dll!Microsoft.PowerShell.PSConsoleReadLine.Complete(bool forward)	Unknown
 	Microsoft.PowerShell.PSReadLine2.dll!Microsoft.PowerShell.PSConsoleReadLine.ViTabCompleteNext(System.ConsoleKeyInfo? key, object arg)	Unknown
```
